# Generated by Django 5.2 on 2025-04-22 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("call_sign", models.CharField(max_length=50)),
                ("vehicle_no", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Policeman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("belt_no", models.CharField(max_length=50, unique=True)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("INSP", "Inspector"),
                            ("SI", "Sub Inspector"),
                            ("ASI", "Assistant Sub Inspector"),
                            ("HC", "Head Constable"),
                            ("CONST", "Constable"),
                            ("HG", "Home Guard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_driver", models.BooleanField(default=False)),
                (
                    "preferred_duty",
                    models.CharField(
                        choices=[("STATIC", "Static"), ("FIELD", "Field")],
                        default="FIELD",
                        max_length=10,
                    ),
                ),
                (
                    "specialized_duty",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("si_count", models.PositiveIntegerField(default=0)),
                ("asi_count", models.PositiveIntegerField(default=0)),
                ("hc_count", models.PositiveIntegerField(default=0)),
                ("constable_count", models.PositiveIntegerField(default=0)),
                ("hgv_count", models.PositiveIntegerField(default=0)),
                ("driver_count", models.PositiveIntegerField(default=0)),
                ("senior_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployments",
                        to="police_roster.area",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="police_roster.zone",
            ),
        ),
    ]
