# Generated by Django 5.2 on 2025-04-22 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police_roster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policeman",
            name="fixed_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_duty_officers",
                to="police_roster.area",
            ),
        ),
        migrations.AddField(
            model_name="policeman",
            name="has_fixed_duty",
            field=models.BooleanField(default=False),
        ),
    ]
