# Generated by Django 5.2 on 2025-04-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police_roster", "0003_policeman_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviousRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("roster_data", models.JSONField()),
                ("repetition_count", models.PositiveIntegerField(default=0)),
                ("same_area_repetition_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Roster 2025-04-22", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("repetition_count", models.PositiveIntegerField(default=0)),
                ("same_area_repetition_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RosterAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("was_previous_zone", models.BooleanField(default=False)),
                ("was_previous_area", models.BooleanField(default=False)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_assignments",
                        to="police_roster.area",
                    ),
                ),
                (
                    "policeman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_assignments",
                        to="police_roster.policeman",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="police_roster.roster",
                    ),
                ),
            ],
            options={
                "unique_together": {("roster", "policeman")},
            },
        ),
    ]
