# Generated by Django 5.2 on 2025-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police_roster", "0004_previousroster_roster_rosterassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="roster",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
