# Generated by Django 5.2 on 2025-04-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police_roster", "0005_roster_is_pending_alter_roster_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="unfulfilled_requirements",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
