# Generated by Django 5.2 on 2025-04-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_roster', '0007_previousroster_unfulfilled_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='name',
            field=models.CharField(default='Roster 2025-04-24', max_length=100),
        ),
        migrations.CreateModel(
            name='CorrigendumChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_roster.area')),
                ('policeman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_roster.policeman')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrigendum_changes', to='police_roster.previousroster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
